### ISSUE TITLE
Update Privilege Level

### ISSUE THREAD

**Issue by jessicasu77** [Code-4-Community/vsc#24]
### Description
Create a PUT endpoint (/user/:email/privilegeLevel) with a requestBody { privilegeLevel: ...} to change a User's (characterized by its email) Privilege Level to the given privilegeLevel. The user1 can update a given user2's privilege level as long as user1 is at least an admin and user1's privilegeLevel is higher or the same as the privilegeLevel that they want to update user2 to.

Right now a PrivilegeLevel is either BASIC or ADMIN however this endpoint will work with future additions to privilege levels with few code changes.

This endpoint is useful since we want to make certain users admin and a User is created in Prisma upon their first login in with Privilege Level BASIC (completed in issue #20)

Frontend:
Create an input field for a user's email, dropdown of privilegeLevels, submit button for admin (and above) level users. The input field will allow Admins to create new Admins.

### Acceptance Criteria

Scenario 1: 
Given that I am an admin and the user I want to update is not an admin, when I make a request to /user/:email/privilege-level with the requestBody { privilegeLevel: ADMIN} then the given user's privilege level changes to ADMIN.

Scenario 2: 
Given that I am not an admin, I should not be able to see the option to update a user

Scenario 3: 
Given that I am an admin and the user I want to update is already an admin, a 400 error will be thrown.

Scenario 4: 
Given that I am an admin, I can update any admin's privilege levels to BASIC

**Comment by yanDavid21** [comment]
nit: should we do another error code? 
we can do something like 400, 401, or 403 (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)
